Update rest.py
Changed line 48 due to breaking changes from the urllib3 package. Without this change, this error occurs when attempting to get a secret value. 

AttributeError: 'HTTPResponse' object has no attribute 'getheader'